# summarizer/serializers.py
from rest_framework import serializers
from .models import Document

class DocumentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Document
        fields = ['id', 'file', 'summary', 'uploaded_at']
        # The client only needs to upload the file.
        # The summary will be generated by the server.
        read_only_fields = ['summary', 'uploaded_at']